name: Deploy Lambda Function

on:
  push:
    paths:
      - 'lambdas/**' # Trigger workflow for any changes in the 'lambdas' directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fetch the last two commits to compare changes

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Identify modified Lambda functions
        id: detect
        run: |
          CHANGED_FOLDERS=$(git diff --name-only HEAD^ HEAD | grep -E '^lambdas/[^/]+/' | awk -F'/' '{print $2}' | sort | uniq || true)
          echo "CHANGED_FOLDERS=$(echo $CHANGED_FOLDERS | tr '\n' ' ')" >> $GITHUB_ENV
          echo "Changed folders: $CHANGED_FOLDERS"

      - name: Deploy Lambda functions
        if: env.CHANGED_FOLDERS
        run: |
          for folder in $CHANGED_FOLDERS; do
            cd lambdas/$folder
            zip -r code.zip .
            aws lambda update-function-code \
              --function-name arn:aws:lambda:ap-south-1:278699821793:function:$folder \
              --zip-file fileb://code.zip
            cd -
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"
