name: Deploy Lambda Function

on:
  push:
    paths:
      - 'lambdas/final/**'
      - 'lambdas/fall_detection/**'
      - '.github/workflows/deploy.yml' # Optional: Re-run for workflow updates

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Identify the changed directory
      - name: Determine Changed Directory
        id: detect-changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q 'lambdas/final/'; then
            echo "lambda_path=lambdas/final" >> $GITHUB_ENV
            echo "lambda_name=final" >> $GITHUB_ENV
          elif git diff --name-only HEAD~1 HEAD | grep -q 'lambdas/fall_detection/'; then
            echo "lambda_path=lambdas/fall_detection" >> $GITHUB_ENV
            echo "lambda_name=fall_detection" >> $GITHUB_ENV
          else
            echo "No relevant changes found."
            exit 0

      # Install zip tool
      - name: Install zip tool
        run: sudo apt-get install zip -y

      # Create Zip file for the changed Lambda function
      - name: Create Zip file
        run: |
          cd ${{ env.lambda_path }}
          zip -r ../code.zip .

      # Update Lambda function code on AWS
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: |
            lambda update-function-code \
              --function-name arn:aws:lambda:eu-north-1:145023099892:function:${{ env.lambda_name }} \
              --zip-file fileb://lambdas/code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
