name: Deploy Lambda Function

on:
  push:
    paths:
      - 'lambdas/**' # Trigger workflow for any changes in the 'lambdas' directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fetch the last two commits to compare changes

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Identify modified Lambda functions
        id: detect
        run: |
          echo "Finding modified files..."
          # List all modified files under 'lambdas/'
          MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD | grep '^lambdas/' || true)
          echo "Modified files:"
          echo "$MODIFIED_FILES"

          # Extract second-level folder names (e.g., car-detection-nht, person-detection-nht)
          CHANGED_FUNCTIONS=$(echo "$MODIFIED_FILES" | awk -F'/' 'NF==3 {print $2}' | sort | uniq)
          echo "Identified changed functions:"
          echo "$CHANGED_FUNCTIONS"

          # Export to the environment for use in subsequent steps
          echo "CHANGED_FUNCTIONS=$(echo $CHANGED_FUNCTIONS | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Deploy Lambda functions
        if: env.CHANGED_FUNCTIONS
        run: |
          echo "Starting deployment process..."
          echo "Functions to deploy: $CHANGED_FUNCTIONS"

          for function_name in $CHANGED_FUNCTIONS; do
            echo "Processing function: $function_name"
            # Navigate to the function folder
            cd lambdas/$function_name
            echo "Zipping contents of folder: lambdas/$function_name"
            ls -R
            zip -r code.zip .
            echo "Updating function: arn:aws:lambda:ap-south-1:278699821793:function:$function_name"
            aws lambda update-function-code \
              --function-name arn:aws:lambda:ap-south-1:278699821793:function:$function_name \
              --zip-file fileb://code.zip
            echo "Deployment for $function_name completed."
            # Return to the previous directory
            cd - >/dev/null
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"
