name: Deploy Lambda Function

on:
  push:
    paths:
      - 'lambdas/**' # Trigger workflow only for changes inside the 'lambdas' directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fetch the last two commits to compare changes

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Identify modified Lambda function
        id: detect
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep -E '^lambdas/[^/]+/lambda_function.py$' || true)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "Changed files: $CHANGED_FILES"

      - name: Deploy Lambda functions
        if: env.CHANGED_FILES
        run: |
          for file in $CHANGED_FILES; do
            FUNCTION_NAME=$(basename $(dirname $file))
            cd $(dirname $file)
            zip -r code.zip .
            aws lambda update-function-code \
              --function-name arn:aws:lambda:eu-north-1:145023099892:function:$FUNCTION_NAME \
              --zip-file fileb://code.zip
            cd -
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-north-1"
