name: Deploy Lambda Function

on:
  push:
    branches: [ main ]
    paths:
      - 'lambdas/final/**'     # Triggers on changes in final lambda
      - 'lambdas/fall_detection/**'  # Triggers on changes in fall_detection lambda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install zip tool
        uses: montudor/action-zip@v1

      # Determine which lambda has changed and create a zip file accordingly
      - name: Create Zip file for final Lambda function
        if: github.event.head_commit.modified | contains('lambdas/final')
        run: |
          cd lambdas/final
          zip -r ../final.zip .

      - name: Create Zip file for fall_detection Lambda function
        if: github.event.head_commit.modified | contains('lambdas/fall_detection')
        run: |
          cd lambdas/fall_detection
          zip -r ../fall_detection.zip .

      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: |
            lambda update-function-code \
              --function-name arn:aws:lambda:eu-north-1:145023099892:function:final \
              --zip-file fileb://final.zip
            lambda update-function-code \
              --function-name arn:aws:lambda:eu-north-1:145023099892:function:fall-detection \
              --zip-file fileb://fall_detection.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-north-1"
