name: Deploy Lambda Function

on:
  push:
    paths:
      - 'lambdas/**' # Trigger workflow for any changes in the 'lambdas' directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fetch the last two commits to compare changes

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Identify modified Lambda functions
        id: detect
        run: |
          # Identify all modified files under 'lambdas', then extract the second-level folder names
          CHANGED_FUNCTIONS=$(git diff --name-only HEAD^ HEAD | grep '^lambdas/' | awk -F'/' '{print $2}' | sort | uniq)
          echo "CHANGED_FUNCTIONS=$(echo $CHANGED_FUNCTIONS | tr '\n' ' ')" >> $GITHUB_ENV
          echo "Changed functions: $CHANGED_FUNCTIONS"

      - name: Deploy Lambda functions
        if: env.CHANGED_FUNCTIONS
        run: |
          for function_name in $CHANGED_FUNCTIONS; do
            # Navigate to the corresponding Lambda function folder
            cd lambdas/$function_name
            # Create a deployment package
            zip -r code.zip .
            # Update the AWS Lambda function
            aws lambda update-function-code \
              --function-name arn:aws:lambda:ap-south-1:278699821793:function:$function_name \
              --zip-file fileb://code.zip
            # Go back to the previous directory
            cd - >/dev/null
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"
