name: Deploy Lambda Function

on:
  push:
    paths:
      - 'lambdas/**' # Trigger workflow for changes in any file within the 'lambdas' directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fetch the last two commits to compare changes

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Identify modified Lambda functions
        id: detect
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep -E '^lambdas/.*/.*$' || true)
          echo "CHANGED_FILES=$(echo $CHANGED_FILES | tr '\n' ' ')" >> $GITHUB_ENV
          echo "Changed files: $CHANGED_FILES"

      - name: Deploy Lambda functions
        if: env.CHANGED_FILES
        run: |
          for file in $CHANGED_FILES; do
            # Get the folder name above the lambda_function.py file
            FUNCTION_NAME=$(echo $file | awk -F'/' '{print $(NF-2)}')
            cd lambdas/$FUNCTION_NAME
            zip -r code.zip .
            aws lambda update-function-code \
              --function-name arn:aws:lambda:ap-south-1:278699821793:function:$FUNCTION_NAME \
              --zip-file fileb://code.zip
            cd -
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"
